services:
  postgres:
    image: postgres:17-alpine
    ports:
      - 8081:5432
    environment:
      - POSTGRES_PASSWORD=x135531x
      - POSTGRES_USER=postgres
      - POSTGRES_DB=encryption_app_data
    networks:
      - encryption_app_network

  api:
    image: encryption-api
    ports:
      - 8080:8080
    depends_on:
      - postgres
    networks:
      - encryption_app_network

networks:
  encryption_app_network:
    driver: bridge